#pragma once

#include <cstddef>
#include <cstdint>

// Declarations for the generated obstacle-detection model. The
// definitions (weights, biases, and quantization scale/zero-point for
// every layer) live entirely in model_data.cc, which is regenerated by
// scripts/generate_model.py — never hand-edit model_data.cc.
namespace edge_ai_quadcopter::model {

inline constexpr std::size_t kInputSize = 16;
inline constexpr std::size_t kHidden1Size = 8;
inline constexpr std::size_t kHidden2Size = 4;
inline constexpr std::size_t kOutputSize = 1;

// Asymmetric INT8 quantization: real_value = scale * (quantized - zero_point)
extern const float kInputScale;
extern const int32_t kInputZeroPoint;

// Weights use symmetric per-tensor quantization (weight_zero_point == 0),
// matching standard full-integer TFLite quantization; only a scale is
// needed. Biases are pre-scaled to the (input_scale * weight_scale) unit
// so acc = bias[j] + sum_i (input_q[i] - input_zero_point) * weight[i, j].
extern const int8_t kLayer1Weights[kInputSize * kHidden1Size];
extern const int32_t kLayer1Bias[kHidden1Size];
extern const float kLayer1WeightScale;
extern const float kLayer1OutputScale;
extern const int32_t kLayer1OutputZeroPoint;

extern const int8_t kLayer2Weights[kHidden1Size * kHidden2Size];
extern const int32_t kLayer2Bias[kHidden2Size];
extern const float kLayer2WeightScale;
extern const float kLayer2OutputScale;
extern const int32_t kLayer2OutputZeroPoint;

extern const int8_t kLayer3Weights[kHidden2Size * kOutputSize];
extern const int32_t kLayer3Bias[kOutputSize];
extern const float kLayer3WeightScale;
extern const float kLayer3OutputScale;
extern const int32_t kLayer3OutputZeroPoint;

}  // namespace edge_ai_quadcopter::model
