// Generated by scripts/generate_model.py — DO NOT EDIT BY HAND.
// Regenerate: python3 scripts/generate_model.py

#include "edge_ai_quadcopter/model_data.h"

namespace edge_ai_quadcopter::model {

const float kInputScale = 0.0313725490f;
const int32_t kInputZeroPoint = -128;

const int8_t kLayer1Weights[128] = {42, 38, 33, -84, 24, -27, -13, 33, 26, 4, -10, -118, 12, 3, -67, -8, -18, -17, -19, -88, 14, 34, 2, -14, -57, -14, -1, -53, 3, 78, -49, 2, -23, -8, -16, -11, -30, 79, -13, -7, -20, 19, -8, 5, -54, 33, 2, 19, 31, 36, -18, 5, -110, 20, 1, -4, 45, -3, -6, 16, -93, -1, 23, -7, 17, -40, -21, 21, -53, -8, 2, 4, 38, -69, -26, 22, -23, 4, 24, -4, 23, -127, -11, 18, 27, 0, -25, 6, 26, -61, -23, 27, 37, 33, -14, 29, 42, -15, -11, 56, 43, 47, -13, 59, 57, 38, -4, 58, 53, 40, 15, 97, 68, 73, 9, 49, 51, 16, -32, 107, 88, 60, -13, -15, 31, 16, -7, 50};
const int32_t kLayer1Bias[8] = {-2217, 340, -3, 128, -8, -1974, -267, -1415};
const float kLayer1WeightScale = 0.0164282415f;
const float kLayer1OutputScale = 0.0211614674f;
const int32_t kLayer1OutputZeroPoint = -128;

const int8_t kLayer2Weights[32] = {-53, -12, 18, 78, 93, 53, -79, -52, -45, -31, 1, 31, 62, -24, -127, -1, 79, -9, -100, 21, 75, 4, 82, -83, -42, 22, -2, -41, -51, -6, 47, -14};
const int32_t kLayer2Bias[4] = {3851, 241, -993, 1104};
const float kLayer2WeightScale = 0.0172981945f;
const float kLayer2OutputScale = 0.0359527926f;
const int32_t kLayer2OutputZeroPoint = -128;

const int8_t kLayer3Weights[4] = {127, 47, -110, 104};
const int32_t kLayer3Bias[1] = {2816};
const float kLayer3WeightScale = 0.0165263230f;
const float kLayer3OutputScale = 0.0039215686f;
const int32_t kLayer3OutputZeroPoint = -128;

}  // namespace edge_ai_quadcopter::model
