# Kernel Features
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=2048

# C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_NEWLIB_LIBC=y

# CAN Bus Support
CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_CAN_NATIVE_LINUX=y
CONFIG_CAN_MAX_FILTER=5
